/* ============================================================
   PACKAGE 1 — DYNAMIC WEBSITE ENGINE
   Do not edit this file for normal agent customization.
   Everything is controlled from config.js.
   ============================================================ */

document.addEventListener("DOMContentLoaded", () => {
  const c = window.siteConfig;

  if (!c || !c.agent || !c.contact) {
    console.error("siteConfig was not loaded. Check config.js.");
    return;
  }

  const $ = (id) => document.getElementById(id);
  const setText = (id, value) => {
    const el = $(id);
    if (el && value !== undefined && value !== null) el.textContent = value;
  };
  const setHref = (id, value) => {
    const el = $(id);
    if (el && value) el.href = value;
  };
  const toggle = (el, show) => {
    if (el) el.style.display = show ? "" : "none";
  };

  const phone = String(c.contact.phone || "").replace(/\D/g, "");
  const wa = String(c.contact.whatsapp || c.contact.phone || "").replace(/\D/g, "");
  const cc = String(c.settings?.whatsappCountryCode || "91").replace(/\D/g, "");
  const waNumber = wa.startsWith(cc) ? wa : cc + wa;
  const waMessage = c.agent.name
    ? `Hello ${c.agent.name}, I would like to know more about insurance planning.`
    : "Hello, I would like to know more about insurance planning.";
  const waLink = waNumber ? `https://wa.me/${waNumber}?text=${encodeURIComponent(waMessage)}` : "#";
  const telLink = phone ? `tel:${phone}` : "#";

  /* ---------- Browser title ---------- */
  document.title = c.site?.browserTitle || `${c.agent.name} | LIC Insurance Advisor`;

/* ---------- Favicon ---------- */

if (c.site?.favicon) {
  let favicon = document.querySelector('link[rel="icon"]');

  if (!favicon) {
    favicon = document.createElement("link");
    favicon.rel = "icon";
    document.head.appendChild(favicon);
  }

  favicon.href = c.site.favicon;
}

  /* ---------- Header / brand ---------- */
  setText("brandName", String(c.site?.brandName || c.agent.name || "Your Name").toUpperCase());
  setText("footerName", String(c.footer?.copyrightName || c.agent.name || "Your Name").toUpperCase());
  setText("footerName2", c.footer?.copyrightName || c.agent.name || "Your Name");
  setText("year", new Date().getFullYear());

  const brandMark = document.querySelector(".brand-mark");
  if (brandMark) brandMark.textContent = c.site?.initials || (c.agent.name || "A").trim().charAt(0).toUpperCase();

  const brandSub = document.querySelector(".brand small");
  if (brandSub) brandSub.textContent = c.site?.brandSubtitle || c.agent.designation || "LIC INSURANCE ADVISOR";

  /* ---------- Animation observer (must be created before dynamic sections) ---------- */
  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add("visible");
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.12 });

  /* ---------- Hero ---------- */
  if (c.hero?.show !== false) {
    const hero = $("home");
    toggle(hero, true);

    const eyebrow = hero?.querySelector(".eyebrow");
    if (eyebrow) eyebrow.innerHTML = `<span></span>${c.hero.eyebrow || ""}`;

    const h1 = hero?.querySelector("h1");
    if (h1) h1.innerHTML = `${c.hero.titleLine1 || ""}<br><em>${c.hero.titleLine2 || ""}</em>`;

    setText("heroText", c.hero.description || "");
    setText("experience", c.agent.experience || "");
    setText("aboutExperience", c.about?.experience || c.agent.experience || "");
    setText("serviceArea", c.about?.area || c.agent.serviceArea || "");

    const heroCall = $("heroCall");
    const heroWa = $("heroWa");
    if (heroCall) {
      heroCall.href = telLink;
      heroCall.innerHTML = `${c.hero.callButtonText || "Call Now"} <span>↗</span>`;
    }
    if (heroWa) {
      heroWa.href = waLink;
      heroWa.innerHTML = `${c.hero.whatsappButtonText || "WhatsApp"} <span>↗</span>`;
    }

    const stats = hero.querySelector(".trust-row");
    if (stats && Array.isArray(c.hero.stats)) {
      stats.innerHTML = c.hero.stats.map((s, i) => `
        ${i ? "<i></i>" : ""}
        <div><strong>${s.number || ""}</strong><span>${s.label || ""}</span></div>
      `).join("");
    }
  } else {
    toggle($("home"), false);
  }

  /* ---------- Agent photo ---------- */
  const photo = $("agentPhoto");
  if (photo) {
    photo.src = c.agent.photo || "images/agent-placeholder.svg";
    photo.alt = `${c.agent.name || "Agent"} - ${c.agent.designation || "LIC Insurance Advisor"}`;
  }

  /* ---------- About ---------- */
  if (c.about?.show !== false) {
    const about = $("about");
    toggle(about, true);
    const eyebrow = about?.querySelector(".eyebrow");
    if (eyebrow) eyebrow.textContent = c.about.eyebrow || "";
    const h2 = about?.querySelector("h2");
    if (h2) h2.innerHTML = `${c.about.titleLine1 || ""}<br><em>${c.about.titleLine2 || ""}</em>`;
    setText("aboutText", c.about.description || c.agent.shortBio || "");
    setText("aboutExperience", c.about.experience || c.agent.experience || "");
    setText("serviceArea", c.about.area || c.agent.serviceArea || "");
    const info = about?.querySelector(".info-pills");
    if (info && c.about.areaLabel) {
      const spans = info.querySelectorAll("span");
      if (spans[0]) spans[0].textContent = c.about.experienceLabel || "Years of experience";
      if (spans[1]) spans[1].textContent = c.about.areaLabel || "Service area";
    }
  } else toggle($("about"), false);

  /* ---------- Services ---------- */
  const servicesSection = $("services");
  if (c.services?.show !== false) {
    toggle(servicesSection, true);
    const eyebrow = servicesSection?.querySelector(".section-heading .eyebrow");
    if (eyebrow) eyebrow.textContent = c.services.eyebrow || "";
    const h2 = servicesSection?.querySelector(".section-heading h2");
    if (h2) h2.innerHTML = `${c.services.titleLine1 || ""}<br><em>${c.services.titleLine2 || ""}</em>`;

    const grid = servicesSection?.querySelector(".service-grid");
    if (grid) {
      const list = Array.isArray(c.services.list) ? c.services.list : [];
      grid.innerHTML = list.map((s, i) => `
        <article class="service-card reveal ${i % 2 ? "reveal-delay" : ""}">
          <span class="service-no">${String(i + 1).padStart(2, "0")}</span>
          <div class="service-icon">${s.icon || "◆"}</div>
          <h3>${s.title || ""}</h3>
          <p>${s.description || ""}</p>
        </article>
      `).join("");
      grid.querySelectorAll(".reveal").forEach(el => observer.observe(el));
    }

    const cta = servicesSection?.querySelector(".cta-strip");
    if (cta) {
      toggle(cta, c.services.cta?.show !== false);
      if (c.services.cta) {
        const e = cta.querySelector(".eyebrow");
        const h = cta.querySelector("h3");
        const b = cta.querySelector(".btn");
        if (e) e.textContent = c.services.cta.eyebrow || "";
        if (h) h.textContent = c.services.cta.title || "";
        if (b) {
          b.href = waLink;
          b.textContent = c.services.cta.buttonText || "Talk on WhatsApp";
          b.innerHTML += " <span>↗</span>";
        }
      }
    }
  } else toggle(servicesSection, false);

  /* ---------- Why Choose Me ---------- */
  const why = $("why");
  if (c.whyChooseMe?.show !== false) {
    toggle(why, true);
    const eyebrow = why?.querySelector(".why-copy .eyebrow");
    if (eyebrow) eyebrow.textContent = c.whyChooseMe.eyebrow || "";
    const h2 = why?.querySelector(".why-copy h2");
    if (h2) h2.innerHTML = `${c.whyChooseMe.titleLine1 || ""}<br><em>${c.whyChooseMe.titleLine2 || ""}</em>`;
    const p = why?.querySelector(".why-copy > p:not(.eyebrow)");
    if (p) p.textContent = c.whyChooseMe.description || "";

    const benefits = why?.querySelector(".benefits");
    if (benefits) {
      benefits.innerHTML = (c.whyChooseMe.list || []).map((b, i) => `
        <div class="benefit reveal">
          <span>${String(i + 1).padStart(2, "0")}</span>
          <div><h3>${b.title || ""}</h3><p>${b.description || ""}</p></div>
        </div>
      `).join("");
      benefits.querySelectorAll(".reveal").forEach(el => observer.observe(el));
    }
  } else toggle(why, false);

  /* ---------- Contact ---------- */
  const contact = $("contact");
  if (c.contactSection?.show !== false) {
    toggle(contact, true);
    const eyebrow = contact?.querySelector(".contact-copy .eyebrow");
    if (eyebrow) eyebrow.textContent = c.contactSection.eyebrow || "";
    const h2 = contact?.querySelector(".contact-copy h2");
    if (h2) h2.innerHTML = `${c.contactSection.titleLine1 || ""}<br><em>${c.contactSection.titleLine2 || ""}</em>`;
    const desc = contact?.querySelector(".contact-copy > p:not(.eyebrow)");
    if (desc) desc.textContent = c.contactSection.description || "";

    setText("phoneText", c.contact.phone || "");
    setText("emailText", c.contact.email || "");
    setText("addressText", [c.contact.address, c.contact.city, c.contact.state, c.contact.pincode].filter(Boolean).join(", "));

    const phoneLink = $("phoneLink");
    const emailLink = $("emailLink");
    if (phoneLink) phoneLink.href = telLink;
    if (emailLink) emailLink.href = `mailto:${c.contact.email || ""}`;

    const qrBox = contact?.querySelector(".qr-placeholder");
    if (qrBox) {
      if (c.contactSection.qr?.show === false) {
        qrBox.style.display = "none";
      } else {
        const qrUrl = waLink !== "#" ? `https://api.qrserver.com/v1/create-qr-code/?size=240x240&margin=8&data=${encodeURIComponent(waLink)}` : "";
        qrBox.innerHTML = qrUrl
          ? `<img src="${qrUrl}" alt="WhatsApp QR Code" style="width:100%;height:100%;object-fit:contain;border-radius:8px;background:#fff;padding:6px">`
          : "QR";
      }
    }
    const qrCaption = contact?.querySelector(".contact-action p");
    if (qrCaption) qrCaption.textContent = c.contactSection.qr?.caption || "Scan or tap to connect";

    const contactWa = $("contactWa");
    const contactCall = $("contactCall");
    if (contactWa) {
      contactWa.href = waLink;
      contactWa.innerHTML = `${c.contactSection.whatsappButtonText || "Chat on WhatsApp"} <span>↗</span>`;
    }
    if (contactCall) {
      contactCall.href = telLink;
      contactCall.innerHTML = `${c.contactSection.callButtonText || "Call Me"} <span>↗</span>`;
    }
    if (c.contact.mapLink) {
      let map = contact.querySelector(".map-link");
      if (!map) {
        map = document.createElement("a");
        map.className = "map-link btn btn-outline dark-outline";
        map.target = "_blank";
        map.rel = "noopener";
        map.textContent = "Open Google Maps ↗";
        contact.querySelector(".contact-copy")?.appendChild(map);
      }
      map.href = c.contact.mapLink;
    }
  } else toggle(contact, false);

  /* ---------- Optional sections: testimonials / FAQ ---------- */
  function injectOptionalSection(id, afterId, content, className) {
    let sec = document.getElementById(id);
    if (!sec) {
      sec = document.createElement("section");
      sec.id = id;
      sec.className = `section ${className || ""}`;
      const after = document.getElementById(afterId);
      after?.insertAdjacentElement("afterend", sec);
    }
    sec.innerHTML = content;
    return sec;
  }

  if (c.testimonials?.show) {
    const cards = (c.testimonials.list || []).map(t => `
      <article class="service-card reveal">
        <div class="service-icon">“</div>
        <h3>${t.name || ""}</h3>
        <p>${t.text || ""}</p>
        <small style="color:var(--muted)">${t.location || ""}</small>
      </article>
    `).join("");
    const sec = injectOptionalSection("testimonials", "why", `
      <div class="container">
        <div class="section-heading reveal">
          <div class="section-label"><span>04</span><b>TESTIMONIALS</b></div>
          <div><p class="eyebrow">${c.testimonials.eyebrow || ""}</p>
          <h2>${c.testimonials.titleLine1 || ""}<br><em>${c.testimonials.titleLine2 || ""}</em></h2></div>
        </div>
        <div class="service-grid">${cards}</div>
      </div>`, "services");
    sec.querySelectorAll(".reveal").forEach(el => observer.observe(el));
  } else {
    document.getElementById("testimonials")?.remove();
  }

  if (c.faq?.show) {
    const items = (c.faq.list || []).map(f => `
      <details class="faq-item">
        <summary>${f.question || ""}</summary>
        <p>${f.answer || ""}</p>
      </details>
    `).join("");
    const sec = injectOptionalSection("faq", "contact", `
      <div class="container">
        <div class="section-heading reveal">
          <div class="section-label"><span>05</span><b>FAQ</b></div>
          <div><p class="eyebrow">${c.faq.eyebrow || ""}</p>
          <h2>${c.faq.titleLine1 || ""}<br><em>${c.faq.titleLine2 || ""}</em></h2></div>
        </div>
        <div class="faq-list">${items}</div>
      </div>`, "about");
    sec.querySelectorAll(".reveal").forEach(el => observer.observe(el));
  } else {
    document.getElementById("faq")?.remove();
  }

  /* ---------- Global contact links ---------- */
  ["headerWa","heroWa","serviceWa","contactWa","floatWa"].forEach(id => {
    const el = $(id);
    if (el) el.href = waLink;
  });
  ["heroCall","phoneLink","contactCall","floatCall"].forEach(id => {
    const el = $(id);
    if (el) el.href = telLink;
  });

  /* ---------- Footer ---------- */
  if (c.footer) {
    const f = document.querySelector("footer");
    toggle(f, c.footer.show !== false);
    const tagline = f?.querySelector(".footer-inner span");
    if (tagline) tagline.textContent = c.footer.tagline || "";
    const back = f?.querySelector(".footer-inner>a");
    if (back) back.textContent = c.footer.backToTopText || "Back to top ↑";
    const p = f?.querySelector(".footer-inner p");
    if (p) p.innerHTML = `© <span id="year">${new Date().getFullYear()}</span> <span id="footerName2">${c.footer.copyrightName || c.agent.name}</span>. ${c.footer.copyrightText || ""}`;
  }

  /* ---------- Floating buttons ---------- */
  const floats = document.querySelector(".floating-actions");
  if (floats) {
    toggle(floats, c.floatingButtons?.show !== false);
    const call = $("floatCall");
    const waBtn = $("floatWa");
    toggle(call, c.floatingButtons?.call?.show !== false);
    toggle(waBtn, c.floatingButtons?.whatsapp?.show !== false);
    if (call) call.title = c.floatingButtons?.call?.tooltip || "Call";
    if (waBtn) waBtn.title = c.floatingButtons?.whatsapp?.tooltip || "WhatsApp";
  }

/* ---------- Social links ---------- */

const socialSection = document.getElementById("social");

if (socialSection) {

  // Show / hide complete Social Media section
  socialSection.style.display =
    c.social?.show === true ? "" : "none";

  if (c.social?.show === true) {

    const socialLinks = {
      facebook: c.social.facebook,
      instagram: c.social.instagram,
      youtube: c.social.youtube,
      linkedin: c.social.linkedin
    };

    Object.entries(socialLinks).forEach(([platform, url]) => {

      const link = socialSection.querySelector(
        `[data-social="${platform}"]`
      );

      if (!link) return;

      if (url && url.trim() !== "") {

        link.href = url;
        link.target = "_blank";
        link.rel = "noopener noreferrer";
        link.style.display = "";

      } else {

        // Hide social platform if no link is provided
        link.style.display = "none";

      }

    });
  }
}
  /* ---------- Scroll / animations ---------- */
  const progress = $("progress");
  const header = $("header");
  window.addEventListener("scroll", () => {
    const h = document.documentElement.scrollHeight - window.innerHeight;
    if (progress) progress.style.width = `${h ? (window.scrollY / h) * 100 : 0}%`;
    header?.classList.toggle("scrolled", window.scrollY > 20);
  }, { passive: true });

  document.querySelectorAll(".reveal").forEach(el => observer.observe(el));

  /* ---------- Mobile menu ---------- */
  const menuBtn = $("menuBtn");
  const nav = $("nav");
  if (c.settings?.mobileMenu !== false) {
    menuBtn?.addEventListener("click", () => {
      const open = nav.classList.toggle("open");
      menuBtn.setAttribute("aria-expanded", open ? "true" : "false");
    });
    nav?.querySelectorAll("a").forEach(link =>
      link.addEventListener("click", () => nav.classList.remove("open"))
    );
  }
});
